@SetLocal EnableDelayedExpansion
REM Set CANDLE_HOME before starting or alter the next line to set installation directory for TEPS
IF "%CANDLE_HOME%" EQU "" SET CANDLE_HOME=C:\IBM\ITM
%CANDLE_HOME%\cnps\KfwSQLClient /e "SELECT SITNAME,SITINFO,REEV_DAYS,REEV_TIME,PDT FROM O4SRV.TSITDESC" >QA1CSITF.DB.LST
%CANDLE_HOME%\cnps\KfwSQLClient /e "SELECT ID,FULLNAME FROM O4SRV.TNAME" >QA1DNAME.DB.LST
%CANDLE_HOME%\cnps\KfwSQLClient /e "SELECT SITNAME,DELTASTAT,ORIGINNODE,LCLTMSTMP,NODE,ATOMIZE FROM O4SRV.TSITSTSH" >QA1CSTSH.DB.LST
@EndLocal
